version: "3"

services:
  database:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network

  backend:
    # container_name: e-com-backend
    image: faizan44/e-com_micro_backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://database:27017/e-commerce
      - PORT=8000
      - HOST=0.0.0.0
    depends_on:
      - database
    networks:
      - my-network

  frontend:
    # container_name: e-com-frontend
    image: faizan44/e-com_micro_frontend
    ports:
      - "3000:3000"
    environment:
      # Ip address of the host
      - REACT_APP_API_URL=http://< IP >/api

    depends_on:
      - backend
    networks:
      - my-network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
#

#

#

# version: "3"

# services:
#   database:
#     image: mongo:4.4.6
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     networks:
#       - my-network

#   # - `sudo docker push faizan44/e-com_micro_frontend`
#   # - `sudo docker push faizan44/e-com_micro_backend`

#   backend:
#     container_name: e-com-backend
#     image: faizan44/e-com_micro_backend
#     # build:
#     #   context: ./backend
#     ports:
#       - "8000:8000"
#     environment:
#       - MONGODB_URI=mongodb://database:27017/e-commerce
#       - PORT=8000
#       - HOST=0.0.0.0
#     depends_on:
#       - database
#     networks:
#       - my-network

#   frontend:
#     container_name: e-com-frontend
#     image: faizan44/e-com_micro_frontend
#     # build:
#     #   context: ./frontend
#     ports:
#       - "3000:3000"
#     environment:
#       - REACT_APP_API_URL=http://localhost:8000/api
#     depends_on:
#       - backend
#     networks:
#       - my-network

# networks:
#   my-network:
#     driver: bridge

# volumes:
#   mongodb_data:
