FROM node:18

# Set the working directory to /app
WORKDIR /app

# copy all
COPY backend/ /app/backend
COPY database/ /app/database

# Install dependencies for backend
WORKDIR /app/backend
RUN npm install

# Install dependencies for database
WORKDIR /app/database
RUN npm install

# Reset working directory
WORKDIR /app

EXPOSE 3000

CMD ["node", "backend/backend.js"]
